name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          [
            'https://front.questionnaire.ip-poc.com/app/home',
            'https://front.paymentgateway.ip-poc.com/app/payment-summary',
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        id: zap-scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ matrix.targets }}

      - name: Save Scan Report for Target 1
        if: matrix.targets[0] == 'https://front.questionnaire.ip-poc.com/app/home'
        run: mv zap-baseline-report.html zap-scan-report-target1-$(date +"%Y%m%d%H%M%S").html

      - name: Save Scan Report for Target 2
        if: matrix.targets[1] == 'https://front.paymentgateway.ip-poc.com/app/payment-summary'
        run: mv zap-baseline-report.html zap-scan-report-target2-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            report_filename="zap-scan-report-${target//[:\/]/_}-$(date +"%Y%m%d%H%M%S").html"
            if grep -q 'Vulnerability Found' "$report_filename"; then
              echo "Security issues found in the scan report for target: $target."
              exit 1  # Exit with an error code to stop the workflow
            else
              echo "No security issues found in the scan report for target: $target."
            fi
          done

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            zap-scan-report-target*.html
