name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          [
            'https://front.questionnaire.ip-poc.com/app/home',
            'https://front.paymentgateway.ip-poc.com/app/payment-summary',
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        id: zap-scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ matrix.targets }}

      - name: Save Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            report_filename="zap-scan-report-${target//[:\/]/_}-$(date +"%Y%m%d%H%M%S").html"
            mv zap-baseline-report.html "$report_filename"
            echo "::set-output name=report_${target//[:\/]/_}::$report_filename"
          done

      - name: Check for Issues in Scan Reports
        id: check-issues
        run: |
          security_issues_found=false
          for target in ${{ matrix.targets }}; do
            report_filename="zap-scan-report-${target//[:\/]/_}-$(date +"%Y%m%d%H%M%S").html"
            if grep -q 'Vulnerability Found' "$report_filename"; then
              echo "Security issues found in the scan report for target: $target."
              security_issues_found=true
            else
              echo "No security issues found in the scan report for target: $target."
            fi
          done
          echo "::set-output name=security_issues::$security_issues_found"

      - name: Fail on Security Issues
        if: steps.check-issues.outputs.security_issues == 'true'
        run: exit 1

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            zap-scan-report-*.html
