name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        targets: ['https://front.questionnaire.ip-poc.com/app/home']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        id: zap-scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ matrix.targets }}

      - name: Save Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            mv report_html.html "zap-scan-report-${target//[:\/]/_}-$(date +"%Y%m%d%H%M%S").html"
          done

      - name: Check for Issues in Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            if grep -q 'Description' "zap-scan-report-${target//[:\/]/_}-"*.html; then
              echo "Security issues found in the scan report for target: $target."
              exit 1  # Exit with an error code to stop the workflow
            else
              echo "No security issues found in the scan report for target: $target."
            fi
          done

      - name: Publish Scan Reports
        if: failure() == true
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            zap-scan-report-*.html
