name: CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # Use the latest version of actions/checkout

      # Set Target URLs as an environment variable
      - name: Set Target URLs
        run: |
          echo "TARGETS=https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge,https://front.questionnaire.ip-poc.com/app/home" >> $GITHUB_ENV

      # Split the list of targets into an array
      - name: Split Target URLs
        id: split-targets
        run: |
          IFS=',' read -ra TARGETS <<< "$TARGETS"
          for target in "${TARGETS[@]}"; do
            echo "Scanning target: $target"
            # Run the OWASP ZAP Baseline Scan for each target
            # Adjust the ZAP command accordingly to use the $target variable
            docker run -d -p 8080:8080 owasp/zap2docker-stable zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true -target "$target"
          done

      # Add your OWASP ZAP Baseline Scan step here (if needed)

      # Add the steps to save, check, and publish the scan reports here
      - name: Save Scan Reports
        run: |
          # Rename the report files to something unique
          for target in "${TARGETS[@]}"; do
            mv zap-baseline-report.html "myreport-$(date +"%Y%m%d%H%M%S")-$target.html"
          done

      - name: Check for Issues in Scan Reports
        run: |
          # Assuming you have a script to check the report for issues (e.g., using a tool like grep)
          for target in "${TARGETS[@]}"; do
            if grep -q 'Vulnerability Found' "myreport-*$target.html"; then
              echo "Security issues found in the scan report for $target."
              exit 1  # Exit with an error code to stop the workflow
            else
              echo "No security issues found in the scan report for $target."
            fi
          done

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: myreport-*.html
