name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Use actions/checkout@v2 for better compatibility

      - name: OWASP ZAP Baseline Scan - Target URL
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://front.questionnaire.ip-poc.com/app/home'

      - name: Save Target URL Scan Report
        run: |
          mv zap-baseline-report.html target-url-report-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Target URL Scan Report
        run: |
          if grep -q 'Vulnerability Found' target-url-report*.html; then
            echo "Security issues found in the target URL scan report."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the target URL scan report."
          fi

      - name: OWASP ZAP Baseline Scan - Repository Code
        uses: zaproxy/action-baseline@v0.7.0
        with:
          # You can specify the path to the code you want to scan
          # For example, you can use '.' to scan the entire repository
          target: .

      - name: Save Repository Code Scan Report
        run: |
          mv zap-baseline-report.html repository-code-report-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Repository Code Scan Report
        run: |
          if grep -q 'Vulnerability Found' repository-code-report*.html; then
            echo "Security issues found in the repository code scan report."
            exit 1  # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the repository code scan report."
          fi

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            target-url-report*.html
            repository-code-report*.html
