name: CI
on:
  push:
    branches:
      - 'development'
  pull_request:
    branches:
      - 'development'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        id: zap-scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://front.questionnaire.ip-poc.com/app/home'

      - name: Save Scan Report
        run: |
          mv zap-baseline-report.html myreport-$(date +"%Y%m%d%H%M%S").html

      - name: Check for Issues in Scan Report
        id: check-issues
        run: |
          if grep -q 'Vulnerability Found' myreport*.html; then
            echo "Security issues found in the scan report."
            echo "::set-output name=security-issues::true"
          else
            echo "No security issues found in the scan report."
            echo "::set-output name=security-issues::false"
          fi

      - name: Stop workflow on security issues
        if: steps.check-issues.outputs.security-issues == 'true'
        run: |
          echo "Security issues found. Stopping the workflow."
          exit 1

      - name: Publish Scan Report
        if: steps.check-issues.outputs.security-issues == 'false'
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: myreport*.html
