name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          [
            'https://front.questionnaire.ip-poc.com/app/home',
            'https://front.paymentgateway.ip-poc.com/app/payment-summary',
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save Scan Reports
        id: save-reports
        run: |
          for target in ${{ matrix.targets }}; do
            # Run OWASP ZAP Baseline Scan for each target
            docker run -t owasp/zap2docker-stable zap-baseline.py -t "$target" -g gen.conf -r "zap-baseline-report-${target//[:\/]/_}-$(date +"%Y%m%d%H%M%S").html"
          done

      - name: Check for Issues in Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            if grep -q 'Vulnerability Found' "zap-baseline-report-${target//[:\/]/_}-"*.html; then
              echo "Security issues found in the scan report for target: $target."
              exit 1  # Exit with an error code to stop the workflow
            else
              echo "No security issues found in the scan report for target: $target."
            fi
          done

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            zap-baseline-report-*.html
