name: CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: your-custom-zap-container:latest # Replace with the name of your custom Docker container
      options: --user root # Run the container as root to install packages (if needed)

    strategy:
      matrix:
        targets:
          - 'https://front.questionnaire.ip-poc.com/app/home'
          - 'https://front.paymentgateway.ip-poc.com/app/payment-summary'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Scan Status
        id: set-scan-status
        run: echo "::set-output name=scan_status::success"

      - name: Scan Targets
        id: scan-targets
        run: |
          for target in ${{ matrix.targets }}; do
            echo "Scanning target: $target"
            zap-baseline.py -t "$target"
            if [ $? -ne 0 ]; then
              echo "Security issues found in the scan report for target: $target."
              echo "::set-output name=scan_status::failure"
            else
              echo "No security issues found in the scan report for target: $target."
            fi
          done

      - name: Fail on Security Issues
        if: steps.set-scan-status.outputs.scan_status == 'failure'
        run: exit 1

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            zap-baseline-report-*.html
