name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        targets:
          - 'https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge'
          # Add other target URLs as needed

    steps:
      - name: Set up Docker
        uses: docker/build-push-action@v2
        with:
          context: . # Specify your build context if needed
          tags: |
            zap-baseline:latest # Specify the Docker image name and tag

      - name: Check Docker Version
        run: docker --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        id: zap-scan
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          target: ${{ matrix.targets }}

      - name: Save Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            mv zap-baseline-report.html "zap-scan-report-${target//[:\/]/_}-$(date +"%Y%m%d%H%M%S").html"
          done

      - name: Check for Issues in Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            if grep -q 'Vulnerability Found' "zap-scan-report-${target//[:\/]/_}-"*.html; then
              echo "Security issues found in the scan report for target: $target."
              exit 1 # Exit with an error code to stop the workflow
            else
              echo "No security issues found in the scan report for target: $target."
            fi
          done

      - name: Publish Scan Reports
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: |
            zap-scan-report-*.html
