name: API Security Scan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  api_security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP API Scan
        id: zap-scan
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          target: 'https://bff.paymentgateway.ip-poc.com/bff/v1/gmo-charge'

      - name: Save Scan Report
        run: |
          mv zap-api-scan-report.json "zap-scan-report-$(date +"%Y%m%d%H%M%S").json"

      - name: Check for Issues in Scan Report
        run: |
          if jq -e '.alerts | length > 0' "zap-scan-report-"*.json; then
            echo "Security issues found in the scan report."
            exit 1 # Exit with an error code to stop the workflow
          else
            echo "No security issues found in the scan report."
          fi

      - name: Publish Scan Report
        if: failure() == false
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: |
            zap-scan-report-*.json
