name: CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: ['https://front.questionnaire.ip-poc.com/app/home']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        id: zap-scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ matrix.targets }}
      - name: Save Scan Reports
        run: |
          for target in ${{ matrix.targets }}; do
            mv report_html.html "myreport-$(date +"%Y%m%d%H%M%S").html"
          done

      - name: Check for Issues in Scan Reports
        id: check-issues
        run: |
          for target in ${{ matrix.targets }}; do
            if grep -q 'Description' "myreport-"*.html; then
              echo "Security issues found in the scan report for target: $target."
              echo "::set-output name=issues-found::true"  # Set an output variable to indicate issues found
              exit 1  # Exit with an error code to stop the workflow
            else
              echo "No security issues found in the scan report for target: $target."
            fi
          done

      - name: Publish Scan Reports
        if: failure() == true
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-reports
          path: myreport-*.html

      - name: Create GitHub Issue
        if: steps.check-issues.outputs.issues-found == 'true'
        run: |
          ISSUE_BODY="Security issues were found in the scan report. See the attached scan report artifacts for details."
          curl -X POST \
           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d '{"title": "Security Issues Found", "body": "'"$ISSUE_BODY"'"}' \
           "https://api.github.com/repos/${{ github.repository }}/issues"
